name: main

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository content
          uses: actions/checkout@v3 # Checkout the repository content to github runner.

        - name: Install Python dependencies
          run: pip install -r requirements.txt
       
        - name: Get data from austin energy
          run: python Austin-Energy.py
        
        - name: Commit file
          run: | 
          git config --local user.email "austin_energy_mix_bot@example.com"
          git config --local user.name "Austin Energy Mix Bot"
          git add out.csv
          git commit -m "gh actions add out.csv"
          git push
