name: main

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository content
          uses: actions/checkout@v3 # Checkout the repository content to github runner.

        - name: Install Python dependencies
          run: pip install -r requirements.txt
       
        - name: Get data from austin energy
          run: python Austin-Energy.py
